# Generated by Django 2.2.4 on 2019-08-03 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('common', '0003_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_reqnum', models.IntegerField(blank=True, null=True, verbose_name='Requisition number')),
                ('order_reqdate', models.DateField(blank=True, null=True, verbose_name='Requisition date')),
                ('order_podate', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
                ('order_desc', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount (NET)')),
                ('order_req', models.CharField(max_length=200, verbose_name='Requester name')),
                ('order_deldate', models.DateField(blank=True, null=True, verbose_name='Delivery date')),
                ('order_paymethod', models.CharField(blank=True, choices=[('C', 'Credit'), ('CC', 'Credit Card'), ('R', 'Reimbursement'), ('PP', 'Pre Payment'), ('PD', 'Per Diem')], max_length=2, null=True, verbose_name='Payment Method')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Expected arrival date')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'permissions': (('view_personnel_orders', 'View personnel Orders'), ('app_access_allorders', 'Access [All orders] app'), ('app_access_orders', 'Access [Orders] app')),
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='orders/orders_files')),
                ('createdon', models.DateField(auto_now_add=True, verbose_name='Created on')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Order file',
                'verbose_name_plural': 'Orders files',
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='OrderExpenseCode',
            fields=[
                ('orderexpensecode_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderexpensecode_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount (EUR)')),
                ('purchase_order', models.CharField(blank=True, max_length=14, verbose_name='Purchase Order')),
                ('expensecode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.ExpenseCode')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Expense Code Information',
                'verbose_name_plural': 'Expense Codes Information',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='expensecode',
            field=models.ManyToManyField(blank=True, through='orders.OrderExpenseCode', to='finance.ExpenseCode'),
        ),
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.ForeignKey(limit_choices_to={'name__startswith': 'GROUP:'}, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='order',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier'),
        ),
    ]
